{{- range .Values.serviceConsumers }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zot-service-cred-{{ .name }}
  namespace: zot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: zot-service-cred-{{ .name }}
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: homelab/service/k8s-zot/{{ .name }}/{{ .cred }}
        property: value
---
{{- end }}
