apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zot-htpasswd
  namespace: zot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: zot-htpasswd
    creationPolicy: Owner
  data:
    - secretKey: htpasswd
      remoteRef:
        key: homelab/zot
        property: HTPASSWD
