apiVersion: v1
kind: ConfigMap
metadata:
  name: zot-verify-script
  namespace: zot
  annotations:
    argocd.argoproj.io/hook: PostSync
data:
{{- (.Files.Glob "scripts/verify.sh").AsConfig | nindent 2 }}
